name: Build & Verify

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    name: IDEA ${{ matrix.idea }} & JDK ${{ matrix.jdk }}
    strategy:
      fail-fast: false
      matrix:
        idea: [ '2026.1.2', '2026.1.3', '2026.1.4', '2026.1.5' ]
        jdk: [ '21' ]
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v6
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}
        cache: gradle

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v2

    - name: build & check
      env:
        ORG_GRADLE_PROJECT_ideaVersion: ${{ matrix.idea }}
      run: ./gradlew build check

    - name: Build Plugin
      env:
        ORG_GRADLE_PROJECT_ideaVersion: ${{ matrix.idea }}
      run: ./gradlew buildPlugin

    - name: Verify Plugin
      env:
        ORG_GRADLE_PROJECT_ideaVersion: ${{ matrix.idea }}
      run: ./gradlew verifyPlugin

    # The verifyPlugin task outputs a report.html that we can upload so it's viewable on the job
    # As archive is set to false (so the HTML is viewable in browser) the path must match a single file
    - name: Upload Verification Report
      uses: actions/upload-artifact@v7
      with:
        name: dlang-plugin-impl-verification-report-${{ matrix.idea }}.html
        path: ${{ github.workspace }}/dlang/plugin-impl/build/reports/pluginVerifier/*/report.html
        retention-days: 3
        overwrite: true
        archive: false
